version: '3.3'

networks:
  network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: treemap:latest
    networks:
      - network
    ports:
      - "5000:5000"
    volumes:
      - app_data:/var/www/html/storage/app/public
    env_file: ./.env
    depends_on:
      - nginx

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - /docker/nginx/conf:/etc/nginx:ro
      - /docker/nginx/www/:/var/www:ro
      - /certs/letsencrypt:/etc/letsencrypt:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/log:/var/log
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network

volumes:
  app_data:
    driver: local
