version: '3.3'

networks:
  network:
    driver: bridge

services:

  postgres:
      image: postgres:14-alpine
      ports:
        - 5432:5432
      volumes:
        - ~/apps/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=treemap_password
        - POSTGRES_USER=treemap_user
        - POSTGRES_DB=treemap

volumes:
  app_data:
    driver: local
