version: '3.3'

networks:
  network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: treemap:latest
    networks:
      - network
    ports:
      - "5000:5000"
    volumes:
      - app_data:/var/www/html/storage/app/public
    env_file: ./.env
    depends_on:
      - nginx

volumes:
  app_data:
    driver: local
