version: '3.3'

networks:
  network:
    driver: bridge

services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    environment:
      DOMAIN: "treemap.services"
    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - ./etc/nginx/templates:/etc/nginx/templates:ro
      - ./etc/letsencrypt:/etc/letsencrypt:ro # mounting the folder to the nginx container
      - ./certbot/data:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    environment:
      DOMAIN: "treemap.services"
      EMAIL: "qouiqaismael890@gmail.com"
    depends_on:
      - nginx
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
      --email qouiqaismael890@gmail.com --agree-tos --no-eff-email
      -d ${DOMAIN}
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
volumes:
  app_data:
    driver: local
