version: '3.3'

networks:
  network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: treemap:latest
    networks:
      - network
    ports:
      - "8000:8000"
    volumes:
      - app_data:/var/www/html/storage/app/public
    env_file: ./.env
    depends_on:
      - nginx

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - app_data:/var/www/html/public/storage
      - /etc/nginx/ssl/live/treemap.services:/etc/nginx/ssl/live/treemap.services

    ports:
      - "80:80"
      - "443:443"
    networks:
      - network

volumes:
  app_data:
    driver: local
