version: '3.3'

networks:
  network:
    driver: bridge

services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    environment:
      DOMAIN: "treemap.services"
    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
volumes:
  app_data:
    driver: local
