FROM nginx:1.17.8-alpine

ADD deploy/nginx/http/conf/nginx.conf /etc/nginx/nginx.conf
ADD deploy/nginx/http/conf/service.conf /etc/nginx/conf.d/service.conf

ADD deploy/nginx/http/script/entrypoint.sh /entrypoint.sh

RUN \
 rm /etc/nginx/conf.d/default.conf && \
 chmod +x /entrypoint.sh && \
 dos2unix /entrypoint.sh && \
 rm -rf /var/cache/apk/* && \
 mkdir -p /var/www/certbot/.well-known/acme-challenge/ && \
 touch Test_File > /var/www/certbot;

CMD ["/entrypoint.sh"]
