version: '3.3'

networks:
  network:
    driver: bridge

services:

  postgres:
      image: postgres:12
      ports:
        - 5432:5432
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        - POSTGRES_DB=treemap
        - POSTGRES_PASSWORD=treemap_password
        - POSTGRES_USER=treemap_user

volumes:
  app_data:
    driver: local
